### ISSUE TITLE
Request for Polymorphius Library Update on npm 🚀 

### ISSUE THREAD

**Issue by Seifenn** [taiga-family/ng-polymorpheus#391]
### Description

The current npm release of Polymorphius lacks support for standalone components, unlike the demo version. This limits integration into projects using new versions of angular. Can the maintainers provide an updated npm release with this support? 

Since importing the library directly by copying the folder of the master into the project directory is not an ideal solution for various reasons, including maintenance and version control concerns. 

Thank you.

**Comment by waterplea** [comment]
New version of polymorpheus was released, but it's under new scope: `@taiga-ui/polymorpheus`, check out latest version. We didn't change the major version because it's a new package and we wanted to sync it with new Taiga UI 4 that is coming soon. It's a breaking change, but that's ok since the package name has changed. It is now standalone and ready to use.
